### ISSUE TITLE
disable changing availability  ?

### ISSUE THREAD

**Issue by MichaelLiss** [azadhmhd/scheduler-calendar#1]
Hi,

How can I turn off changing the availability for a date ? 

I do not want to be able to make any changes to availability on 1 Jan 2021 as it is in the past.  
In other words, I do not want the edit availability screens to show up when I click a date in the past. 

or for any day that I choose (for whatever reason)

**Comment by ASHIQUE-KV** [comment]
Hey @MichaelLiss , 

We have accepted your request and put an 'isPastAvailabilityLocked' boolean for locking disabled dates, you could easily set 'availabilityType' prop  as 'range' and every disabled dates out of your specific range can't be accessed by end user.
