### ISSUE TITLE
clicking on availability time does not fill time values in editing window

### ISSUE THREAD

**Issue by MichaelLiss** [azadhmhd/scheduler-calendar#2]
Hi

Here is the code that exhibits the issue.
```
            <SchedulerCalendar
              availabilities={[
                { day: 'mon', slots: [{ from: '9:00', to: '10:00' }] },
                { day: '1/6/2021', slots: [{ from: '11:00', to: '13:00' }] },
              ]}
              availabilityType={'rolling'}
              duration={0}
              onIntervalChange={() => {}}
            />
```

When I click on the _Monday_ availabilities, the time gets populated, 
however, when I click on the specific date (eg 1/6/2021 11 to 1pm) to edit it, the time does not get filled in 
see image:

![calendar_issue](https://user-images.githubusercontent.com/39492750/103807929-0514a200-500c-11eb-956a-5cc5f67fd12a.png)

**Comment by ASHIQUE-KV** [comment]
Hey @MichaelLiss ,

Sorry the date format on the example was wrong it should be YEAR-MONTH-DAY. 
EX:-  
`<SchedulerCalendar
              availabilities={[
                {
                  day: "mon",
                  slots: [
                    {from: '09:00', to: '10:30'},
                    {from: '11:30', to: '13:00'},
                    {from: '14:30', to: '17:00'},
                  ]
                },
                {
                  day: "2021-01-26",
                  slots: [
                    {from: '09:00', to: '10:30'},
                    {from: '11:30', to: '19:00'},
                  ]
                },
              ]}
              availabilityType={'infinity'}
              duration={10}
              onIntervalChange={() => {}}
            />`

**Comment by MichaelLiss** [comment]
thanks !
