### ISSUE TITLE
Can I change the font color of the number for the date?

### ISSUE THREAD

**Issue by MichaelLiss** [azadhmhd/scheduler-calendar#3]
Hi,

I'd like to be able to change the font color of the date, dependent upon my customization of the day.

In other words, I'd like to have any days date red if there is no availability and green if there is any availability and grey if it has not yet been determined (like next month)

Basically, I want to control the color of the date, based on what happens on that day.

thanks

**Comment by Mishhub** [comment]
Hey @MichaelLiss,
We have created **stylesOfDay** prop (  #12 ), which you can use to customise according to your needs. 
In your case, you can return a function similar to this

`const stylesOfDay = (day: string, isAvailable: boolean, isRolling: boolean ) => {`

    if(!isRolling)
      return Styles.disabledContainer // { color: 'grey' }
    else if(isAvailable)
      return Styles.availableContainer // { color: 'green' }
    else
      return Styles.emptyContainer // { color: 'red' }
  }
